const Notification = require("../../models/member1-kumara/Notification");
const User = require("../../models/member1-kumara/User");
const { sendEmail } = require("../../utils/mailer");

const {
  severityLabel,
  pickStationId,
  decideAlertLevel,
  cooldownMinutes,
  buildDedupeKey,
} = require("../../utils/alertPolicy");

// -------------------------
// Helpers
// -------------------------
function levelFromSeverityText(sev) {
  const s = String(sev || "").toLowerCase();
  if (s === "critical") return 3;
  if (s === "warning") return 2;
  if (s === "advisory" || s === "info") return 1;
  return 0;
}

function htmlEmailTemplate({ title, stationId, severity, message, summary, rowsPreview }) {
  return `
  <div style="font-family:Arial,sans-serif;line-height:1.5">
    <h2 style="margin:0 0 8px">${title}</h2>
    <p style="margin:0 0 10px">
      <b>Station:</b> ${stationId}<br/>
      <b>Severity:</b> ${severity}<br/>
      ${summary ? `<b>Summary:</b> ${summary}<br/>` : ""}
    </p>
    ${message ? `<p style="padding:10px;border-left:4px solid #d32f2f;background:#fff4f4">${message}</p>` : ""}
    ${rowsPreview?.length ? `
      <h3>Top Anomalies</h3>
      <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-size:13px">
        <thead>
          <tr>
            <th>Day</th><th>Fuel</th><th>Prob</th><th>Reason</th>
          </tr>
        </thead>
        <tbody>
          ${rowsPreview.map(r => `
            <tr>
              <td>${r.day || ""}</td>
              <td>${r.fuelType || r.fuel_type || ""}</td>
              <td>${Number(r.prob ?? r.prob_irregular ?? 0).toFixed(3)}</td>
              <td>${(r.reason || "").toString().slice(0,160)}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
    ` : ""}
    <p style="margin-top:14px;color:#666;font-size:12px">
      FuelWatch Alert System • This message was generated by the anomaly detection module.
    </p>
  </div>
  `;
}

// -------------------------
// GET recipients for UI
// /api/notifications/recipients?station_id=Premium%20Tank%2003
// -------------------------
async function getRecipients(req, res) {
  try {
    const station_id = String(req.query.station_id || "").trim();

    // fetch active management users
    const q = {
      is_active: true,
      role: { $in: ["SUPERVISOR", "MANAGER", "SENIOR_MANAGER"] },
    };

    // optional station filter: if station_id is stored
    // allow users with empty station_id too (global managers)
    if (station_id) {
      q.$or = [{ station_id }, { station_id: "" }, { station_id: { $exists: false } }];
    }

    const users = await User.find(q).select("full_name email role station_id").lean();

    return res.json({
      ok: true,
      station_id: station_id || null,
      recipients: users,
    });
  } catch (e) {
    return res.status(500).json({ ok: false, error: String(e?.message || e) });
  }
}

// -------------------------
// Existing: list notifications
// -------------------------
async function listNotifications(req, res) {
  try {
    const items = await Notification.find().sort({ createdAt: -1 }).limit(50).lean();
    return res.json({ ok: true, items });
  } catch (e) {
    return res.status(500).json({ ok: false, error: String(e?.message || e) });
  }
}

// -------------------------
// Existing: notify from scan (button old workflow)
// -------------------------
async function notifyFromScan(req, res) {
  try {
    const payload = req.body || {};
    const rows = Array.isArray(payload.rows) ? payload.rows : [];
    const events = Array.isArray(payload.events) ? payload.events : [];

    const stationId = payload.station_id || pickStationId(payload) || "UNKNOWN";
    const level = decideAlertLevel({ rows, events });
    const severity = severityLabel(level);

    const roles = level >= 3
      ? ["SUPERVISOR", "MANAGER", "SENIOR_MANAGER"]
      : level === 2
      ? ["SUPERVISOR", "MANAGER"]
      : level === 1
      ? ["SUPERVISOR"]
      : [];

    if (!roles.length) {
      const doc = await Notification.create({
        source: "misbehavior_scan",
        triggered_by: "manual",
        station_id: stationId,
        alert_level: level,
        severity,
        channel: "email",
        recipients: [],
        status: "suppressed",
        error: "No anomalies flagged",
        payload,
      });
      return res.json({ ok: true, status: doc.status, message: "No anomalies to notify.", doc });
    }

    const recipients = await User.find({
      is_active: true,
      role: { $in: roles },
      $or: [{ station_id: stationId }, { station_id: "" }, { station_id: { $exists: false } }],
    }).select("email full_name role").lean();

    const emails = recipients.map(r => r.email).filter(Boolean);

    if (!emails.length) {
      const doc = await Notification.create({
        source: "misbehavior_scan",
        triggered_by: "manual",
        station_id: stationId,
        alert_level: level,
        severity,
        channel: "email",
        recipients: [],
        status: "failed",
        error: "No recipients found. Add users with roles SUPERVISOR/MANAGER/SENIOR_MANAGER.",
        payload,
      });
      return res.json({ ok: true, status: doc.status, message: doc.error, doc });
    }

    const dedupe_key = buildDedupeKey({ stationId, level, rows });
    const cooldown = cooldownMinutes(level);

    const recent = await Notification.findOne({
      dedupe_key,
      createdAt: { $gte: new Date(Date.now() - cooldown * 60 * 1000) },
      status: { $in: ["sent", "suppressed"] },
    }).lean();

    if (recent) {
      const doc = await Notification.create({
        source: "misbehavior_scan",
        triggered_by: "manual",
        station_id: stationId,
        alert_level: level,
        severity,
        channel: "email",
        recipients: emails,
        dedupe_key,
        status: "suppressed",
        error: `Cooldown active (${cooldown} min).`,
        payload,
      });
      return res.json({ ok: true, status: doc.status, message: doc.error, doc });
    }

    const subject = `FuelWatch ${severity} Alert • Station ${stationId}`;
    const preview = rows.filter(r => (r.pred === 1 || r.pred === true)).slice(0, 6);

    const html = htmlEmailTemplate({
      title: "FuelWatch Anomaly Alert",
      stationId,
      severity,
      message: payload.message || "",
      summary: `Flagged anomalies detected. Level=${level}`,
      rowsPreview: preview,
    });

    let mailResult = null;
    try {
      mailResult = await sendEmail({ to: emails, subject, html });
    } catch (err) {
      const doc = await Notification.create({
        source: "misbehavior_scan",
        triggered_by: "manual",
        station_id: stationId,
        alert_level: level,
        severity,
        channel: "email",
        recipients: emails,
        dedupe_key,
        status: "failed",
        error: String(err?.message || err),
        payload,
      });
      return res.json({ ok: true, status: doc.status, message: doc.error, doc });
    }

    const doc = await Notification.create({
      source: "misbehavior_scan",
      triggered_by: "manual",
      station_id: stationId,
      alert_level: level,
      severity,
      channel: "email",
      recipients: emails,
      dedupe_key,
      status: "sent",
      sent_at: new Date(),
      payload,
      mail_result: mailResult,
    });

    return res.json({ ok: true, status: doc.status, message: "Notification sent", doc });
  } catch (e) {
    return res.status(500).json({ ok: false, error: String(e?.message || e) });
  }
}

// -------------------------
// ✅ NEW: Send manual notification from form
// POST /api/notifications/send-manual
// -------------------------
async function sendManualNotification(req, res) {
  try {
    const body = req.body || {};

    const stationId = String(body.station_id || "UNKNOWN").trim() || "UNKNOWN";
    const channel = String(body.channel || "email").toLowerCase();
    const roles = Array.isArray(body.roles) ? body.roles : [];
    const severityText = String(body.severity || "Warning"); // Advisory/Warning/Critical
    const message = String(body.message || "").trim();

    const rows = Array.isArray(body.rows) ? body.rows : [];
    const events = Array.isArray(body.events) ? body.events : [];
    const file_name = String(body.file_name || "").trim();
    const threshold = body.threshold;

    // decide level: use selected severity if provided, otherwise auto
    let level = levelFromSeverityText(severityText);
    if (!level) level = decideAlertLevel({ rows, events });

    const severity = severityLabel(level);

    if (!roles.length) {
      return res.status(400).json({
        ok: false,
        error: "Please select at least one recipient role (SUPERVISOR/MANAGER/SENIOR_MANAGER).",
      });
    }

    const recipients = await User.find({
      is_active: true,
      role: { $in: roles },
      $or: [{ station_id: stationId }, { station_id: "" }, { station_id: { $exists: false } }],
    }).select("email full_name role").lean();

    const emails = recipients.map(r => r.email).filter(Boolean);

    if (!emails.length) {
      const doc = await Notification.create({
        source: "misbehavior_scan",
        triggered_by: "manual_form",
        station_id: stationId,
        alert_level: level,
        severity,
        channel,
        recipients: [],
        status: "failed",
        error: "No recipients found in DB for selected roles/station.",
        payload: body,
      });

      return res.json({ ok: true, status: doc.status, message: doc.error, doc });
    }

    const dedupe_key = buildDedupeKey({ stationId, level, rows });
    const cooldown = cooldownMinutes(level);

    const recent = await Notification.findOne({
      dedupe_key,
      createdAt: { $gte: new Date(Date.now() - cooldown * 60 * 1000) },
      status: { $in: ["sent", "suppressed"] },
    }).lean();

    if (recent) {
      const doc = await Notification.create({
        source: "misbehavior_scan",
        triggered_by: "manual_form",
        station_id: stationId,
        alert_level: level,
        severity,
        channel,
        recipients: emails,
        dedupe_key,
        status: "suppressed",
        error: `Cooldown active (${cooldown} min).`,
        payload: body,
      });

      return res.json({ ok: true, status: doc.status, message: doc.error, doc });
    }

    // Send
    let mailResult = null;
    if (channel === "email") {
      const subject = `FuelWatch ${severity} Alert • Station ${stationId}`;
      const preview = rows.filter(r => (r.pred === 1 || r.pred === true)).slice(0, 6);

      const html = htmlEmailTemplate({
        title: "FuelWatch Manual Alert",
        stationId,
        severity,
        message,
        summary: `File: ${file_name || "—"} • Threshold: ${threshold ?? "—"}`,
        rowsPreview: preview,
      });

      try {
        mailResult = await sendEmail({ to: emails, subject, html });
      } catch (err) {
        const doc = await Notification.create({
          source: "misbehavior_scan",
          triggered_by: "manual_form",
          station_id: stationId,
          alert_level: level,
          severity,
          channel,
          recipients: emails,
          dedupe_key,
          status: "failed",
          error: String(err?.message || err),
          payload: body,
        });

        return res.json({ ok: true, status: doc.status, message: doc.error, doc });
      }
    }

    const doc = await Notification.create({
      source: "misbehavior_scan",
      triggered_by: "manual_form",
      station_id: stationId,
      alert_level: level,
      severity,
      channel,
      recipients: emails,
      dedupe_key,
      status: "sent",
      sent_at: new Date(),
      payload: body,
      mail_result: mailResult,
    });

    return res.json({ ok: true, status: doc.status, message: "Alert sent successfully", doc });
  } catch (e) {
    return res.status(500).json({ ok: false, error: String(e?.message || e) });
  }
}

module.exports = {
  notifyFromScan,
  listNotifications,
  getRecipients,
  sendManualNotification,
};
